### PR TITLE
fix #560 sorting songs by album also considers disc and track number

### LINKED ISSUE #560: Sorting by album sorts songs alphabetically instead of by track number
When you sort the "Songs" view by Album, the individual songs in an album will be sorted alphabetically, not by track number as they should be.

image

### PR DESCRIPTION
**Pull request by dermeck**
Sorting by album now sorts the songs of the same album by disc and track number instead of name.

### CODE REVIEW

**Comment by digimezzo** [comment]
Thanks a lot for this pull request. This change makes a lot of sense.

**Comment by dermeck** [comment]
@digimezzo sorry for the red test (again), I'll fix that

**Comment by dermeck** [comment]
@digimezzo I just checked, does not seem to be related to these changes  (just saw that there were other changes to ordering, so I'll leave it)

**Comment by digimezzo** [comment]
@dermeck Oh, I didn't pay attention to the tests. I'll have a look.

**Pull request merged**
