### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by RealDrPuc**
Added es (Español) to constants.ts
Added es.json

### CODE REVIEW

**Comment by g-yui** [comment]
Fairly good translation, well done :D

**Comment by elJoa** [comment]
Ty! If you have any suggestions, don't mind sharing them :)

**Comment by digimezzo** [comment]
Hi! Sorry for checking this out so late. The UI wasn't mature enough back then to apply new translations. It is now. If you're still interested, could you update your PR to the new translation format? I'd be glad to add it to master. Thanks!

**Comment by RealDrPuc** [comment]
For sure! I'll try to do it tomorrow.

**Pull request closed without merging**
