### PR TITLE
Create Croatian (hr-hr) translation

### PR DESCRIPTION
**Pull request by anotherus3r**
Add the Croatian (hr-hr) translation for Dopamine.

### CODE REVIEW

**Comment by digimezzo** [comment]
Hi! Sorry for checking this out so late. The UI wasn't mature enough back then to apply new translations. It is now. If you're still interested, could you update your PR to the new translation format? I'd be glad to add it to master. Thanks!

**Comment by anotherus3r** [comment]
@digimezzo Sure! I'll try to do it as soon as I got the time to.

**Comment by anotherus3r** [comment]
@digimezzo I've updated the translation format.

**Comment by digimezzo** [comment]
Thanks!

**Pull request merged**
