### PR TITLE
Bugfix/550 + MacOS traffic lights support

### PR DESCRIPTION
**Pull request by fr-eed**
Fixes close/exit window behavior on MacOS specified in [issue550](https://github.com/digimezzo/dopamine/issues/550)
Adds support of MacOS traffic lights

### CODE REVIEW

**Comment by digimezzo** [comment]
@fr-eed Thank you for this PR. I've planned to give the mac build some love in Preview 34. Preview 33 will be released today. After that, I'll  start with preview 34 and will review your PR.

**Comment by digimezzo** [comment]
@fr-eed I've reviewed and tested your PR. Looks great! Just one issue, there is a serious UI performance git caused by appearanceService.needsTrafficLightMargin being called continuously. That call happening continuously is OK, however, it's calling this.desktop.isMacOS in property appearanceService.needsTrafficLightMargin that causes the performance hit. Getting isMaOS should be handled like this._windowHasNativeTitleBar in appearanceService. It shoudl be fetched once from main during appearanceService.initialize(). Coudl you modify that? If you'd rather have me do it, let me know. I can merge the PR and make the change after merging.

**Comment by fr-eed** [comment]
I'll modify that. I've also found another bug with fullscreen on MacOS related to this PR that I'll fix

**Comment by digimezzo** [comment]
@fr-eed Thanks for the change. Just wondering, How did you notice the fullscreen issue? There is currently no logic to put the window fullscreen.

**Comment by fr-eed** [comment]
Green traffic light button enters fullscreen by default on MacOS, unlike on Windows it doesn't just maximize an app

**Comment by digimezzo** [comment]
> Green traffic light button enters fullscreen by default on MacOS, unlike on Windows it doesn't just maximize an app

Thanks for clarifying. Code looks good. I'm merging.

**Pull request merged**
